-- SQL Insert statements for Modulos table
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Técnicas generales de laboratorio (1º)', 1, '1º', '1368-SAN301');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Gestión de muestras biológicas (1º)', 1, '1º', '1367-SAN301');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Biología molecular y citogenética (1º)', 1, '1º', '1369-SAN301');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Fisiopatología general (1º)', 1, '1º', '1370-SAN301');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Necropsias (2º)', 2, '2º', '1379-SAN301');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Procesamiento citológico y tisular (2º)', 2, '2º', '1380-SAN301');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Citología ginecológica (2º)', 2, '2º', '1381-SAN301');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Citología general (2º)', 2, '2º', '1382-SAN301');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Proyecto de Anatomía Patológica y citodiagnóstico (2º)', 2, '2º', '1383-SAN301');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Formación y orientación laboral (1º)', 1, '1º', '1356-SAN305');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Empresa e iniciativa emprendedora (1º)', 1, '1º', '1385-SAN301');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Formación en centros de trabajo (2º)', 2, '2º', '1358-SAN305');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Lengua extranjera profesional: inglés1 (1º)', 1, '1º', 'A115-SAN305');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Lengua extranjera profesional: inglés2 (2º)', 2, '2º', 'A116-SAN305');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Actividades físico-deportivas de equipo (2º)', 4, '2º', '1140-AFD301');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Primeros auxilios y socorrismo acuático (2º)', 4, '2º', '008-AFD301');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Organización y gestión de una pequeña empresa de actividades de tiempo libre y socioeducativas (2º)', 4, '2º', '009-AFD301');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Actividades físicas para personas con discapacidades (2º)', 4, '2º', '010-AFD301');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Formación y orientación laboral (2º)', 4, '2º', '011-AFD301');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Fundamentos biológicos y bases del acondicionamiento físico (1º)', 3, '1º', '002-AFD301');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Formación en centros de trabajo (2º)', 4, '2º', '1358-SAN305');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Animación y dinámica de grupos (1º)', 3, '1º', '006-AFD301');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Actividades físico-deportivas con implementos (1º)', 3, '1º', '003-AFD301');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Juegos y actividades físicas recreativas para animación (1º)', 3, '1º', '004-AFD301');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Actividades físico-deportivas individuales (1º)', 3, '1º', '1139-AFD301');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Metodología didáctica de las actividades físico-deportivas (1º)', 3, '1º', '005-AFD301');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Conducción de grupos a caballo y cuidados equinos básicos (1º)', 5, '1º', '002-AFD201');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Formación en centros d etrabajo (1º)', 5, '1º', '009-AFD201');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Formación y orientación laboral (1º)', 5, '1º', '1356-SAN305');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Dinámica de grupos (1º)', 5, '1º', '007-AFD201');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Actividades físicas para personas con discapacidades (1º)', 5, '1º', '006-AFD201');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Fundamentos biológicos, salud y primeros auxilios (1º)', 5, '1º', '004-AFD201');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Conducción de grupos en bicicleta (1º)', 5, '1º', '003-AFD201');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Desplazamiento, estancia y seguridad en el medio terrestre (1º)', 5, '1º', '001-AFD201');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Administración, gestión y comercialización en la pequeña empresa (1º)', 5, '1º', '005-AFD201');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Operaciones administrativas y documentación sanitaria (1º)', 7, '1º', '005-SAN201');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Técnicas básicas de enfermería (1º)', 7, '1º', '001-SAN201');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Higiene del medio hospitalario y limpieza de material (1º)', 7, '1º', '002-SAN201');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Promoción de la salud y apoyo psicológico al paciente (1º)', 7, '1º', '003-SAN201');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Técnicas de ayuda odontológica/estomatológica (1º)', 7, '1º', '004-SAN201');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Formación en centros de trabajo (2º)', 8, '2º', '1358-SAN305');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Formación y orientación laboral (1º)', 7, '1º', '1356-SAN305');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Relaciones en el equipo de trabajo (1º)', 7, '1º', '006-SAN201');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Bases de Datos (1º)', 9, '1º', '0484-IFC302');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Sistemas informáticos (1º)', 9, '1º', '0483-IFC302');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Sistemas de gestión empresarial (2º)', 10, '2º', '0491-IFC302');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Programación (1º)', 9, '1º', '0485-IFC302');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Formación y orientación laboral (1º)', 9, '1º', '1356-SAN305');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Lengua extranjera profesional: inglés2 (2º)', 10, '2º', 'A116-SAN305');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Formación en centros de trabajo (2º)', 10, '2º', '1358-SAN305');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Empresa e iniciativa emprendedora (2º)', 10, '2º', '1341-AFD201');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Lenguajes de marcas y sistemas de gestión de información (1º)', 9, '1º', '0373-IFC302');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Entornos de desarrollo (1º)', 9, '1º', '0487-IFC302');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Programación de servicios y procesos (2º)', 10, '2º', '0490-IFC302');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Programación multimedia y dispositivos móviles (2º)', 10, '2º', '0489-IFC302');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Desarrollo de interfaces (2º)', 10, '2º', '0488-IFC302');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Acceso a datos (2º)', 10, '2º', '0486-IFC302');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Lengua extranjera profesional: inglés1 (1º)', 9, '1º', 'A115-SAN305');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Proyecto de Desarrollo de Aplicaciones Multiplataforma (2º)', 10, '2º', '0492-IFC302');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Fisiopatología aplicada a la dietética (1º)', 11, '1º', '002-SAN302');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Control alimentario (1º)', 11, '1º', '003-SAN302');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Organización y gestión del área de trabajo asignada en la unidad/gabinete de dietética (1º)', 11, '1º', '004-SAN302');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Relaciones en el entorno de trabajo (1º)', 11, '1º', '005-SAN302');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Formación en centros de trabajo (2º)', 12, '2º', '1358-SAN305');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Formación y orientación laboral (1º)', 11, '1º', '1356-SAN305');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Educación sanitaria y promoción de la salud (2º)', 12, '2º', '009-SAN302');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Dietoterapia (2º)', 12, '2º', '007-SAN302');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Microbiología e higiene alimentaria (2º)', 12, '2º', '008-SAN302');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Alimentación equilibrada (1º)', 11, '1º', '001-SAN302');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Juegos y actividades físico-recreativas y de animación (1º)', 13, '1º', '1138-AFD301');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Actividades físico-deportivas para la inclusión social (2º)', 14, '2º', '1142-AFD301');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Actividades de ocio y tiempo libre (2º)', 14, '2º', '1123-AFD301');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Dinamización grupal (1º)', 13, '1º', '1124-AFD301');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Valoración de la condición física e intervención en accidentes (1º)', 13, '1º', '1136-AFD301');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Planificación de la animación sociodeportiva (2º)', 14, '2º', '1137-AFD301');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Actividades físico-deportivas de equipo (2º)', 14, '2º', '1140-AFD301');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Actividades físico-deportivas de implementos (2º)', 14, '2º', '1141-AFD301');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Formación en centros de trabajo (2º)', 14, '2º', '1358-SAN305');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Metodología de la enseñanza de actividades físico-deportivas (1º)', 13, '1º', '1143-AFD301');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Proyecto de Enseñanza y Animación Sociodeportiva (2º)', 14, '2º', '1144-AFD301');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Formación y orientación laboral (1º)', 13, '1º', '1356-SAN305');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Empresa e iniciativa emprendedora (2º)', 14, '2º', '1341-AFD201');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Lengua extranjera profesional: inglés1 (1º)', 13, '1º', 'A115-SAN305');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Lengua extranjera profesional: inglés2 (2º)', 14, '2º', 'A116-SAN305');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Actividades físico-deportivas individuales (1º)', 13, '1º', '1139-AFD301');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Oficina de farmacia (1º)', 15, '1º', '0100-SAN202');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Formulación magistral (2º)', 16, '2º', '0104-SAN202');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Primeros auxilios (1º)', 15, '1º', '0020-SAN202');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Anatomofisiología y Patología básicas (1º)', 15, '1º', '0061-SAN202');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Formación en centros de trabajo (2º)', 16, '2º', '1358-SAN305');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Promoción de la salud (2º)', 16, '2º', '0105-SAN202');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Dispensación de productos parafarmacéuticos (2º)', 16, '2º', '0102-SAN202');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Formación y orientación laboral (1º)', 15, '1º', '1356-SAN305');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Operaciones básicas de laboratorio (1º)', 15, '1º', '0103-SAN202');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Dispensación de productos farmacéuticos (1º)', 15, '1º', '0101-SAN202');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Disposición y venta de productos (1º)', 15, '1º', '0099-SAN202');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Empresa e iniciativa emprendedora (2º)', 16, '2º', '1341-AFD201');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Socorrismo en el medio natural (2º)', 18, '2º', '1337-AFD201');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Técnicas de natación (1º)', 17, '1º', '1336-AFD201');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Empresa e iniciativa emprendedora (2º)', 18, '2º', '1341-AFD201');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Formación y orientación laboral (1º)', 17, '1º', '1356-SAN305');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Formación en centros de trabajo (2º)', 18, '2º', '1358-SAN305');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Guía en el medio natural acuático (2º)', 18, '2º', '1338-AFD201');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Guía de bicicleta (1º)', 17, '1º', '1334-AFD201');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Guía de baja y media montaña (1º)', 17, '1º', '1333-AFD201');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Organización de itinerarios (1º)', 17, '1º', '1329-AFD201');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Atención a grupos (1º)', 17, '1º', '1328-AFD201');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Guía ecuestre (2º)', 18, '2º', '1327-AFD201');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Técnicas de equitación (1º)', 17, '1º', '1325-AFD201');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Maniobras con cuerdas (2º)', 18, '2º', '1339-AFD201');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Técnicas de tiempo libre (2º)', 18, '2º', '1335-AFD201');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Técnicas de radiología simple (2º)', 20, '2º', '1349-SAN305');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Proyecto de Imagen para el Diagnóstico y Medicina Nuclear (2º)', 20, '2º', '1355-SAN305');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Técnicas de imagen en medicina nuclear (2º)', 20, '2º', '1353-SAN305');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Técnicas de imagen por resonancia magnética (2º)', 20, '2º', '1352-SAN305');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Lengua extranjera profesional: inglés2 (2º)', 20, '2º', 'A116-SAN305');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Técnicas de radiología especial (2º)', 20, '2º', '1350-SAN305');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Formación y orientación laboral (1º)', 19, '1º', '1356-SAN305');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Técnicas de radiofarmacia (2º)', 20, '2º', '1354-SAN305');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Formación en centros de trabajo (2º)', 20, '2º', '1358-SAN305');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Protección radiológica (1º)', 19, '1º', '1348-SAN305');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Fundamentos físicos y equipos (1º)', 19, '1º', '1346-SAN305');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Atención al paciente (1º)', 19, '1º', '1345-SAN305');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Anatomía por la imagen ( 1º )', 19, '1º', '1347-SAN305');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Empresa e iniciativa emprendedora ( 1º)', 19, '1º', '1357-SAN305');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Técnicas de tomografía computarizada y ecografía (2º)', 20, '2º', '1351-SAN305');
INSERT INTO Modulos (nombre, id_ciclo, curso, codigo_modulo) VALUES ('Lengua extranjera profesional: inglés1 (1º)', 19, '1º', 'A115-SAN305');