/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IntroducirActaRouteImport } from './routes/introducir-acta'
import { Route as EstudiantesRouteImport } from './routes/estudiantes'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const IntroducirActaRoute = IntroducirActaRouteImport.update({
  id: '/introducir-acta',
  path: '/introducir-acta',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudiantesRoute = EstudiantesRouteImport.update({
  id: '/estudiantes',
  path: '/estudiantes',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/estudiantes': typeof EstudiantesRoute
  '/introducir-acta': typeof IntroducirActaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/estudiantes': typeof EstudiantesRoute
  '/introducir-acta': typeof IntroducirActaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/estudiantes': typeof EstudiantesRoute
  '/introducir-acta': typeof IntroducirActaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/estudiantes' | '/introducir-acta'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/estudiantes' | '/introducir-acta'
  id: '__root__' | '/' | '/about' | '/estudiantes' | '/introducir-acta'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  EstudiantesRoute: typeof EstudiantesRoute
  IntroducirActaRoute: typeof IntroducirActaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/introducir-acta': {
      id: '/introducir-acta'
      path: '/introducir-acta'
      fullPath: '/introducir-acta'
      preLoaderRoute: typeof IntroducirActaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudiantes': {
      id: '/estudiantes'
      path: '/estudiantes'
      fullPath: '/estudiantes'
      preLoaderRoute: typeof EstudiantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  EstudiantesRoute: EstudiantesRoute,
  IntroducirActaRoute: IntroducirActaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
