/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IntroducirActaRouteImport } from './routes/introducir-acta'
import { Route as EstudiantesRouteImport } from './routes/estudiantes'
import { Route as IndexRouteImport } from './routes/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntroducirActaRoute = IntroducirActaRouteImport.update({
  id: '/introducir-acta',
  path: '/introducir-acta',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudiantesRoute = EstudiantesRouteImport.update({
  id: '/estudiantes',
  path: '/estudiantes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/estudiantes': typeof EstudiantesRoute
  '/introducir-acta': typeof IntroducirActaRoute
  '/login': typeof LoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/estudiantes': typeof EstudiantesRoute
  '/introducir-acta': typeof IntroducirActaRoute
  '/login': typeof LoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/estudiantes': typeof EstudiantesRoute
  '/introducir-acta': typeof IntroducirActaRoute
  '/login': typeof LoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/estudiantes' | '/introducir-acta' | '/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/estudiantes' | '/introducir-acta' | '/login'
  id: '__root__' | '/' | '/estudiantes' | '/introducir-acta' | '/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EstudiantesRoute: typeof EstudiantesRoute
  IntroducirActaRoute: typeof IntroducirActaRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/introducir-acta': {
      id: '/introducir-acta'
      path: '/introducir-acta'
      fullPath: '/introducir-acta'
      preLoaderRoute: typeof IntroducirActaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudiantes': {
      id: '/estudiantes'
      path: '/estudiantes'
      fullPath: '/estudiantes'
      preLoaderRoute: typeof EstudiantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EstudiantesRoute: EstudiantesRoute,
  IntroducirActaRoute: IntroducirActaRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
